name    'puppet-hyper_v'
version '0.1.0'
source 'https://github.com/openstack-hyper-v/puppet-hyper_v'
author 'puppet'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

dependency 'joshcooper/powershell'
dependency 'openstack-hyper-v/puppet-windows_common'
