name    'openstack-hyper-v-hyper_v'
version '0.1.0'
source 'https://github.com/openstack-hyper-v/puppet-hyper_v.git'
author 'Peter Pouliot <peter@pouliot.net>'
license 'Apache License, Version 2.0'
summary 'Puppet module for installing and using the Microsoft Hyper-V Hypervisor'
description 'Puppet module for installing and using the Microsoft Hyper-V Hypervisor'
project_page 'https://github.com/openstack-hyper-v/puppet-hyper_v'
dependency 'puppetlabs/powershell'
dependency 'openstack-hyper-v/windows_common'
